export {
	type ApiLimits,
	type ApiMeta,
	ApiMetaValidationError,
	type ApiVersionMetadata,
	ApiVersionMismatchError,
	type ApiVersionNegotiation,
	negotiateApiVersion,
	parseApiMeta,
} from "./api-meta.ts";
export {
	type ApiAccessTokenProvider,
	type ApiClient,
	type ApiClientMetadata,
	type ApiClientMetadataProvider,
	type ApiClientOptions,
	type ApiClientPlatform,
	createApiClient,
	type InsecureTransportPolicy,
} from "./client.ts";
export {
	ApiError,
	type ApiProblem,
	type ApiProblemFieldError,
	normalizeApiError,
} from "./errors.ts";
export type {
	AcceptTeamInvitationResponse,
	AddVaultMemberInput,
	ApiPageRequest,
	ApiReadOptions,
	ApiResult,
	ApiWriteOptions,
	Attachment,
	AttachmentDownload,
	AttachmentUploadInput,
	AttachmentUsage,
	AuditEvents,
	AuditEventsRequest,
	AuthUser,
	AuthVaultKey,
	AvailableTeamMember,
	BillingEntitlements,
	BillingStatus,
	BulkImportInput,
	BulkImportResponse,
	CheckoutSession,
	CheckoutSessionInput,
	ConvertVaultInput,
	ConvertVaultResponse,
	CreateAttachmentInput,
	CreateAttachmentResponse,
	CreateItemInput,
	CreateItemResponse,
	CreateShareLinkInput,
	CreateShareLinkResponse,
	CreateTeamInput,
	CreateVaultInput,
	CreateVaultResponse,
	DeleteAccountInput,
	DeletedVaultItem,
	DisableTravelModeInput,
	EmailChangeInput,
	EmailCheckInput,
	EmailCheckResponse,
	EmailShareAccessInput,
	EmailShareVerificationInput,
	FavoriteInput,
	FinishLoginInput,
	FinishLoginResponse,
	HiddenVaultsInput,
	ImageUploadInput,
	LoginAttempt,
	MoveItemInput,
	PasswordChangeInput,
	PendingTeamInvitation,
	PortalSession,
	PresignedUpload,
	PublicShareAccess,
	PublicShareInfo,
	PublicTeamInvitation,
	RecoveryData,
	RecoveryKeyInput,
	RecoverySessionInput,
	RecoveryVerificationInput,
	RefreshSessionResponse,
	RegistrationStatus,
	RemoveTeamMemberInput,
	RemoveTeamMemberResponse,
	RemoveVaultMemberInput,
	RemoveVaultMemberResponse,
	RenameSessionInput,
	ResendTeamInvitationResponse,
	ResetPasswordInput,
	ResetPasswordResponse,
	SecretKeyRotationInput,
	SendTeamInvitationInput,
	SendTeamInvitationResponse,
	Session,
	ShareAccessLog,
	ShareLinkList,
	SignupInput,
	SignupResponse,
	SignupVerificationInput,
	StartLoginInput,
	SyncBootstrapItem,
	SyncBootstrapPage,
	SyncChanges,
	SyncEvent,
	TeamDetails,
	TeamImageUploadInput,
	TeamInvitation,
	TeamLeaveInput,
	TeamMember,
	TeamMemberAccess,
	TeamRotationData,
	TeamSeatInvoicePreview,
	TeamSummary,
	TeamVault,
	TravelMode,
	UpdateAttachmentInput,
	UpdateItemInput,
	UpdateItemResponse,
	UpdateTeamInput,
	UpdateVaultInput,
	UpdateVaultMemberRoleInput,
	UpdateVaultResponse,
	Vault,
	VaultDetails,
	VaultItem,
	VaultItemDetails,
	VaultMember,
	VaultRotationData,
	VaultStats,
	VerifyRecoveryInput,
	VerifyRecoveryResponse,
	VerifySignupVerificationInput,
	VerifySignupVerificationResponse,
} from "./facade-types.ts";
export {
	ApiValueValidationError,
	parseDecimalString,
	parseRfc3339Utc,
} from "./value-codecs.ts";
