export {
	type ApiLimits,
	type ApiMeta,
	ApiMetaValidationError,
	type ApiVersionMetadata,
	ApiVersionMismatchError,
	type ApiVersionNegotiation,
	negotiateApiVersion,
	parseApiMeta,
} from "./api-meta.ts";
export {
	type ApiAccessTokenProvider,
	type ApiClient,
	type ApiClientMetadata,
	type ApiClientMetadataProvider,
	type ApiClientOptions,
	type ApiClientPlatform,
	type ApiFetch,
	type ApiRequestOrigin,
	createApiClient,
	type InsecureTransportPolicy,
} from "./client.ts";
export {
	ApiError,
	type ApiProblem,
	type ApiProblemFieldError,
	isApiErrorStatus,
	isUnauthorizedApiError,
	normalizeApiError,
} from "./errors.ts";
export type {
	AcceptTeamInvitationResponse,
	AddVaultMemberInput,
	ApiPageRequest,
	ApiResult,
	ApiWriteOptions,
	Attachment,
	AttachmentDownload,
	AttachmentUpload,
	AttachmentUploadInput,
	AttachmentUsage,
	AuditEvent,
	AuditEvents,
	AuditEventsRequest,
	AuthUser,
	AuthVaultKey,
	AvailableTeamMember,
	BillingEntitlements,
	BillingPlan,
	BillingStatus,
	BillingStatusSummary,
	BulkImportInput,
	BulkImportResponse,
	CheckoutSession,
	CheckoutSessionInput,
	ConvertVaultInput,
	ConvertVaultResponse,
	CreateAttachmentInput,
	CreateAttachmentResponse,
	CreateItemInput,
	CreateItemOperationOutcome,
	CreateItemWriteOptions,
	CreateTeamInput,
	CreateVaultInput,
	CreateVaultResponse,
	DeleteAccountInput,
	DeleteAccountResponse,
	DeletedVaultItem,
	DisableTravelModeInput,
	EmailChangeInput,
	EmailCheckInput,
	EmailCheckResponse,
	EmailShareAccessInput,
	EmailShareVerificationInput,
	ErrorCode,
	FavoriteInput,
	FinishLoginInput,
	FinishLoginResponse,
	HiddenVaultsInput,
	ImageUploadInput,
	InvitationStatus,
	ItemCategory,
	ItemOperationOutcome,
	ItemOperationResult,
	ItemOperationWriteOptions,
	ItemPayload,
	LoginAttempt,
	MoveItemInput,
	OperationOutcome,
	OperationRejectionCode,
	PasswordChangeInput,
	PendingTeamInvitation,
	PortalSession,
	PresignedUpload,
	PublicShareAccess,
	PublicShareInfo,
	PublicTeamInvitation,
	RecoveryData,
	RecoveryKeyInput,
	RecoverySessionInput,
	RecoveryVerificationInput,
	RefreshSessionResponse,
	RegistrationStatus,
	RenameSessionInput,
	ResendTeamInvitationResponse,
	ResetPasswordInput,
	ResetPasswordResponse,
	RotationPlanSet,
	RotationPlanSetFinalizeInput,
	RotationPlanSetFinalizeResponse,
	RotationPreparationPage,
	RotationStageInput,
	SecretKeyRotationInput,
	SendTeamInvitationInput,
	SendTeamInvitationResponse,
	Session,
	ShareAccessLog,
	ShareLinkAccessMode,
	ShareLinkList,
	ShareLinkStatus,
	SignupInput,
	SignupResponse,
	SignupVerificationInput,
	StartLoginInput,
	SyncBootstrapItem,
	SyncBootstrapPage,
	SyncBootstrapRequest,
	SyncChanges,
	SyncEntityType,
	SyncEvent,
	SyncEventType,
	TeamDetails,
	TeamImageUploadInput,
	TeamInvitation,
	TeamMember,
	TeamMemberAccess,
	TeamRole,
	TeamSeatInvoicePreview,
	TeamSummary,
	TeamType,
	TeamVault,
	TravelMode,
	UpdateAttachmentInput,
	UpdateItemInput,
	UpdateTeamInput,
	UpdateVaultInput,
	UpdateVaultMemberRoleInput,
	UpdateVaultResponse,
	Vault,
	VaultDetails,
	VaultItem,
	VaultItemDetails,
	VaultMember,
	VaultRole,
	VaultStats,
	VaultType,
	VerifyRecoveryInput,
	VerifyRecoveryResponse,
	VerifySignupVerificationInput,
	VerifySignupVerificationResponse,
} from "./facade-types.ts";
export {
	ApiTransportError,
	classifyHttpServerUrl,
	type HttpServerUrlClassification,
	isApiTransportError,
} from "./transport.ts";
export {
	ApiValueValidationError,
	parseDecimalString,
	parseRfc3339Utc,
} from "./value-codecs.ts";
