// Generated by uniffi-bindgen-react-native
#include "bittery-crypto-react-native.h"
#include "generated/bittery_crypto_api.hpp"

namespace bittery_cryptoreactnative {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeBitteryCryptoApi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}