packages:
  - apps/*
  - packages/*
  - packages/crypto/core
  - packages/crypto/wasm
  - packages/crypto/port
  - packages/crypto/react-native

catalog:
  '@types/react': ~19.2.18
  '@types/react-dom': ~19.2.7
  dotenv: ^17.4.2
  react: 19.2.8
  react-dom: 19.2.8
  zod: ^4.5.4

onlyBuiltDependencies:
  - less
