packages:
  - apps/*
  - packages/*
  - packages/crypto/core
  - packages/crypto/wasm
  - packages/crypto/napi
  - packages/crypto/port
  - packages/crypto/expo-module

catalog:
  '@qubit-rs/client': ^0.4.5
  '@types/react': ~19.1.9
  '@types/react-dom': ~19.1.7
  dotenv: ^17.2.2
  hono: ^4.8.2
  react: 19.1.0
  react-dom: 19.1.0
  zod: ^4.1.13

onlyBuiltDependencies:
  - less
