// Generated by uniffi-bindgen-react-native, then composed by build-wasm.sh.
// Export the generated bindings to the app.
export * from "./generated/bittery_crypto_api";

// Keep Runtime construction and legacy crypto calls on the same initialized instance.
import * as bittery_crypto_api from "./generated/bittery_crypto_api";
import initAsync, { WebClientRuntime } from "./generated/wasm-bindgen/index.js";

export { WebClientRuntime };

const wasmPath = new URL(
  "./generated/wasm-bindgen/index_bg.wasm",
  import.meta.url,
);
type InitInput = Parameters<typeof initAsync>[0];
let initialization: Promise<void> | undefined;

export function uniffiInitAsync(
  moduleOrPath: InitInput = { module_or_path: wasmPath },
): Promise<void> {
  initialization ??= initAsync(moduleOrPath)
    .then(() => {
      bittery_crypto_api.default.initialize();
    })
    .catch((error: unknown) => {
      initialization = undefined;
      throw error;
    });
  return initialization;
}

// Export the crates as individually namespaced objects.
export default {
  bittery_crypto_api,
};
