/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as VaultRouteRouteImport } from './routes/vault/route'
import { Route as VaultIndexRouteImport } from './routes/vault/index'
import { Route as VaultSearchRouteImport } from './routes/vault/search'
import { Route as VaultSettingsRouteImport } from './routes/vault/settings'
import { Route as VaultTagsRouteImport } from './routes/vault/tags'
import { Route as VaultTrashRouteImport } from './routes/vault/trash'
import { Route as VaultIdIndexRouteImport } from './routes/vault/$id/index'
import { Route as VaultAllItemsIndexRouteImport } from './routes/vault/all-items/index'
import { Route as VaultFavoritesIndexRouteImport } from './routes/vault/favorites/index'
import { Route as VaultIdItemIdIndexRouteImport } from './routes/vault/$id/$itemId/index'
import { Route as VaultAllItemsItemIdIndexRouteImport } from './routes/vault/all-items/$itemId/index'
import { Route as VaultFavoritesItemIdIndexRouteImport } from './routes/vault/favorites/$itemId/index'
import { Route as VaultTagTagNameIndexRouteImport } from './routes/vault/tag/$tagName/index'
import { Route as VaultTagTagNameItemIdIndexRouteImport } from './routes/vault/tag/$tagName/$itemId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRouteRoute = VaultRouteRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultSearchRoute = VaultSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultSettingsRoute = VaultSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultTagsRoute = VaultTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultTrashRoute = VaultTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultIdIndexRoute = VaultIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultAllItemsIndexRoute = VaultAllItemsIndexRouteImport.update({
  id: '/all-items/',
  path: '/all-items/',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultFavoritesIndexRoute = VaultFavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultIdItemIdIndexRoute = VaultIdItemIdIndexRouteImport.update({
  id: '/$id/$itemId/',
  path: '/$id/$itemId/',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultAllItemsItemIdIndexRoute =
  VaultAllItemsItemIdIndexRouteImport.update({
    id: '/all-items/$itemId/',
    path: '/all-items/$itemId/',
    getParentRoute: () => VaultRouteRoute,
  } as any)
const VaultFavoritesItemIdIndexRoute =
  VaultFavoritesItemIdIndexRouteImport.update({
    id: '/favorites/$itemId/',
    path: '/favorites/$itemId/',
    getParentRoute: () => VaultRouteRoute,
  } as any)
const VaultTagTagNameIndexRoute = VaultTagTagNameIndexRouteImport.update({
  id: '/tag/$tagName/',
  path: '/tag/$tagName/',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultTagTagNameItemIdIndexRoute =
  VaultTagTagNameItemIdIndexRouteImport.update({
    id: '/tag/$tagName/$itemId/',
    path: '/tag/$tagName/$itemId/',
    getParentRoute: () => VaultRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vault': typeof VaultRouteRouteWithChildren
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/unlock': typeof UnlockRoute
  '/vault/search': typeof VaultSearchRoute
  '/vault/settings': typeof VaultSettingsRoute
  '/vault/tags': typeof VaultTagsRoute
  '/vault/trash': typeof VaultTrashRoute
  '/vault/': typeof VaultIndexRoute
  '/vault/$id/': typeof VaultIdIndexRoute
  '/vault/all-items/': typeof VaultAllItemsIndexRoute
  '/vault/favorites/': typeof VaultFavoritesIndexRoute
  '/vault/$id/$itemId/': typeof VaultIdItemIdIndexRoute
  '/vault/all-items/$itemId/': typeof VaultAllItemsItemIdIndexRoute
  '/vault/favorites/$itemId/': typeof VaultFavoritesItemIdIndexRoute
  '/vault/tag/$tagName/': typeof VaultTagTagNameIndexRoute
  '/vault/tag/$tagName/$itemId/': typeof VaultTagTagNameItemIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/unlock': typeof UnlockRoute
  '/vault/search': typeof VaultSearchRoute
  '/vault/settings': typeof VaultSettingsRoute
  '/vault/tags': typeof VaultTagsRoute
  '/vault/trash': typeof VaultTrashRoute
  '/vault': typeof VaultIndexRoute
  '/vault/$id': typeof VaultIdIndexRoute
  '/vault/all-items': typeof VaultAllItemsIndexRoute
  '/vault/favorites': typeof VaultFavoritesIndexRoute
  '/vault/$id/$itemId': typeof VaultIdItemIdIndexRoute
  '/vault/all-items/$itemId': typeof VaultAllItemsItemIdIndexRoute
  '/vault/favorites/$itemId': typeof VaultFavoritesItemIdIndexRoute
  '/vault/tag/$tagName': typeof VaultTagTagNameIndexRoute
  '/vault/tag/$tagName/$itemId': typeof VaultTagTagNameItemIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vault': typeof VaultRouteRouteWithChildren
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/unlock': typeof UnlockRoute
  '/vault/search': typeof VaultSearchRoute
  '/vault/settings': typeof VaultSettingsRoute
  '/vault/tags': typeof VaultTagsRoute
  '/vault/trash': typeof VaultTrashRoute
  '/vault/': typeof VaultIndexRoute
  '/vault/$id/': typeof VaultIdIndexRoute
  '/vault/all-items/': typeof VaultAllItemsIndexRoute
  '/vault/favorites/': typeof VaultFavoritesIndexRoute
  '/vault/$id/$itemId/': typeof VaultIdItemIdIndexRoute
  '/vault/all-items/$itemId/': typeof VaultAllItemsItemIdIndexRoute
  '/vault/favorites/$itemId/': typeof VaultFavoritesItemIdIndexRoute
  '/vault/tag/$tagName/': typeof VaultTagTagNameIndexRoute
  '/vault/tag/$tagName/$itemId/': typeof VaultTagTagNameItemIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vault'
    | '/debug'
    | '/login'
    | '/unlock'
    | '/vault/search'
    | '/vault/settings'
    | '/vault/tags'
    | '/vault/trash'
    | '/vault/'
    | '/vault/$id/'
    | '/vault/all-items/'
    | '/vault/favorites/'
    | '/vault/$id/$itemId/'
    | '/vault/all-items/$itemId/'
    | '/vault/favorites/$itemId/'
    | '/vault/tag/$tagName/'
    | '/vault/tag/$tagName/$itemId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/login'
    | '/unlock'
    | '/vault/search'
    | '/vault/settings'
    | '/vault/tags'
    | '/vault/trash'
    | '/vault'
    | '/vault/$id'
    | '/vault/all-items'
    | '/vault/favorites'
    | '/vault/$id/$itemId'
    | '/vault/all-items/$itemId'
    | '/vault/favorites/$itemId'
    | '/vault/tag/$tagName'
    | '/vault/tag/$tagName/$itemId'
  id:
    | '__root__'
    | '/'
    | '/vault'
    | '/debug'
    | '/login'
    | '/unlock'
    | '/vault/search'
    | '/vault/settings'
    | '/vault/tags'
    | '/vault/trash'
    | '/vault/'
    | '/vault/$id/'
    | '/vault/all-items/'
    | '/vault/favorites/'
    | '/vault/$id/$itemId/'
    | '/vault/all-items/$itemId/'
    | '/vault/favorites/$itemId/'
    | '/vault/tag/$tagName/'
    | '/vault/tag/$tagName/$itemId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VaultRouteRoute: typeof VaultRouteRouteWithChildren
  DebugRoute: typeof DebugRoute
  LoginRoute: typeof LoginRoute
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/': {
      id: '/vault/'
      path: '/'
      fullPath: '/vault/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/search': {
      id: '/vault/search'
      path: '/search'
      fullPath: '/vault/search'
      preLoaderRoute: typeof VaultSearchRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/settings': {
      id: '/vault/settings'
      path: '/settings'
      fullPath: '/vault/settings'
      preLoaderRoute: typeof VaultSettingsRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/tags': {
      id: '/vault/tags'
      path: '/tags'
      fullPath: '/vault/tags'
      preLoaderRoute: typeof VaultTagsRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/trash': {
      id: '/vault/trash'
      path: '/trash'
      fullPath: '/vault/trash'
      preLoaderRoute: typeof VaultTrashRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/$id/': {
      id: '/vault/$id/'
      path: '/$id'
      fullPath: '/vault/$id/'
      preLoaderRoute: typeof VaultIdIndexRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/all-items/': {
      id: '/vault/all-items/'
      path: '/all-items'
      fullPath: '/vault/all-items/'
      preLoaderRoute: typeof VaultAllItemsIndexRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/favorites/': {
      id: '/vault/favorites/'
      path: '/favorites'
      fullPath: '/vault/favorites/'
      preLoaderRoute: typeof VaultFavoritesIndexRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/$id/$itemId/': {
      id: '/vault/$id/$itemId/'
      path: '/$id/$itemId'
      fullPath: '/vault/$id/$itemId/'
      preLoaderRoute: typeof VaultIdItemIdIndexRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/all-items/$itemId/': {
      id: '/vault/all-items/$itemId/'
      path: '/all-items/$itemId'
      fullPath: '/vault/all-items/$itemId/'
      preLoaderRoute: typeof VaultAllItemsItemIdIndexRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/favorites/$itemId/': {
      id: '/vault/favorites/$itemId/'
      path: '/favorites/$itemId'
      fullPath: '/vault/favorites/$itemId/'
      preLoaderRoute: typeof VaultFavoritesItemIdIndexRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/tag/$tagName/': {
      id: '/vault/tag/$tagName/'
      path: '/tag/$tagName'
      fullPath: '/vault/tag/$tagName/'
      preLoaderRoute: typeof VaultTagTagNameIndexRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/tag/$tagName/$itemId/': {
      id: '/vault/tag/$tagName/$itemId/'
      path: '/tag/$tagName/$itemId'
      fullPath: '/vault/tag/$tagName/$itemId/'
      preLoaderRoute: typeof VaultTagTagNameItemIdIndexRouteImport
      parentRoute: typeof VaultRouteRoute
    }
  }
}

interface VaultRouteRouteChildren {
  VaultSearchRoute: typeof VaultSearchRoute
  VaultSettingsRoute: typeof VaultSettingsRoute
  VaultTagsRoute: typeof VaultTagsRoute
  VaultTrashRoute: typeof VaultTrashRoute
  VaultIndexRoute: typeof VaultIndexRoute
  VaultIdIndexRoute: typeof VaultIdIndexRoute
  VaultAllItemsIndexRoute: typeof VaultAllItemsIndexRoute
  VaultFavoritesIndexRoute: typeof VaultFavoritesIndexRoute
  VaultIdItemIdIndexRoute: typeof VaultIdItemIdIndexRoute
  VaultAllItemsItemIdIndexRoute: typeof VaultAllItemsItemIdIndexRoute
  VaultFavoritesItemIdIndexRoute: typeof VaultFavoritesItemIdIndexRoute
  VaultTagTagNameIndexRoute: typeof VaultTagTagNameIndexRoute
  VaultTagTagNameItemIdIndexRoute: typeof VaultTagTagNameItemIdIndexRoute
}

const VaultRouteRouteChildren: VaultRouteRouteChildren = {
  VaultSearchRoute: VaultSearchRoute,
  VaultSettingsRoute: VaultSettingsRoute,
  VaultTagsRoute: VaultTagsRoute,
  VaultTrashRoute: VaultTrashRoute,
  VaultIndexRoute: VaultIndexRoute,
  VaultIdIndexRoute: VaultIdIndexRoute,
  VaultAllItemsIndexRoute: VaultAllItemsIndexRoute,
  VaultFavoritesIndexRoute: VaultFavoritesIndexRoute,
  VaultIdItemIdIndexRoute: VaultIdItemIdIndexRoute,
  VaultAllItemsItemIdIndexRoute: VaultAllItemsItemIdIndexRoute,
  VaultFavoritesItemIdIndexRoute: VaultFavoritesItemIdIndexRoute,
  VaultTagTagNameIndexRoute: VaultTagTagNameIndexRoute,
  VaultTagTagNameItemIdIndexRoute: VaultTagTagNameItemIdIndexRoute,
}

const VaultRouteRouteWithChildren = VaultRouteRoute._addFileChildren(
  VaultRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VaultRouteRoute: VaultRouteRouteWithChildren,
  DebugRoute: DebugRoute,
  LoginRoute: LoginRoute,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
