/// Command names are the ACL identity of the plugin: each one becomes an
/// `allow-…`/`deny-…` permission under `permissions/autogenerated/`, and
/// `permissions/default.toml` has to list them by hand.
const COMMANDS: &[&str] = &[
    "secret_set",
    "secret_get",
    "secret_delete",
    "secret_available",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
