/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthRecoverRouteImport } from './routes/_auth/recover'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSecurityRouteImport } from './routes/_app/security'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppVaultsIndexRouteImport } from './routes/_app/vaults/index'
import { Route as AppTeamIndexRouteImport } from './routes/_app/team/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AuthInviteTokenRouteImport } from './routes/_auth/invite.$token'
import { Route as AppVaultsTrashRouteImport } from './routes/_app/vaults/trash'
import { Route as AppVaultsVaultIdIndexRouteImport } from './routes/_app/vaults/$vaultId/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecoverRoute = AuthRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultsIndexRoute = AppVaultsIndexRouteImport.update({
  id: '/vaults/',
  path: '/vaults/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamIndexRoute = AppTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AuthInviteTokenRoute = AuthInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AuthRoute,
} as any)
const AppVaultsTrashRoute = AppVaultsTrashRouteImport.update({
  id: '/vaults/trash',
  path: '/vaults/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultsVaultIdIndexRoute = AppVaultsVaultIdIndexRouteImport.update({
  id: '/vaults/$vaultId/',
  path: '/vaults/$vaultId/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof AppBillingRoute
  '/home': typeof AppHomeRoute
  '/security': typeof AppSecurityRoute
  '/login': typeof AuthLoginRoute
  '/recover': typeof AuthRecoverRoute
  '/signup': typeof AuthSignupRoute
  '/share/$token': typeof ShareTokenRoute
  '/vaults/trash': typeof AppVaultsTrashRoute
  '/invite/$token': typeof AuthInviteTokenRoute
  '/admin/': typeof AppAdminIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/team/': typeof AppTeamIndexRoute
  '/vaults/': typeof AppVaultsIndexRoute
  '/vaults/$vaultId/': typeof AppVaultsVaultIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof AppBillingRoute
  '/home': typeof AppHomeRoute
  '/security': typeof AppSecurityRoute
  '/login': typeof AuthLoginRoute
  '/recover': typeof AuthRecoverRoute
  '/signup': typeof AuthSignupRoute
  '/share/$token': typeof ShareTokenRoute
  '/vaults/trash': typeof AppVaultsTrashRoute
  '/invite/$token': typeof AuthInviteTokenRoute
  '/admin': typeof AppAdminIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/team': typeof AppTeamIndexRoute
  '/vaults': typeof AppVaultsIndexRoute
  '/vaults/$vaultId': typeof AppVaultsVaultIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/billing': typeof AppBillingRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/security': typeof AppSecurityRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/recover': typeof AuthRecoverRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/share/$token': typeof ShareTokenRoute
  '/_app/vaults/trash': typeof AppVaultsTrashRoute
  '/_auth/invite/$token': typeof AuthInviteTokenRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/team/': typeof AppTeamIndexRoute
  '/_app/vaults/': typeof AppVaultsIndexRoute
  '/_app/vaults/$vaultId/': typeof AppVaultsVaultIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/home'
    | '/security'
    | '/login'
    | '/recover'
    | '/signup'
    | '/share/$token'
    | '/vaults/trash'
    | '/invite/$token'
    | '/admin/'
    | '/settings/'
    | '/team/'
    | '/vaults/'
    | '/vaults/$vaultId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/home'
    | '/security'
    | '/login'
    | '/recover'
    | '/signup'
    | '/share/$token'
    | '/vaults/trash'
    | '/invite/$token'
    | '/admin'
    | '/settings'
    | '/team'
    | '/vaults'
    | '/vaults/$vaultId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/billing'
    | '/_app/home'
    | '/_app/security'
    | '/_auth/login'
    | '/_auth/recover'
    | '/_auth/signup'
    | '/share/$token'
    | '/_app/vaults/trash'
    | '/_auth/invite/$token'
    | '/_app/admin/'
    | '/_app/settings/'
    | '/_app/team/'
    | '/_app/vaults/'
    | '/_app/vaults/$vaultId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/recover': {
      id: '/_auth/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof AuthRecoverRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vaults/': {
      id: '/_app/vaults/'
      path: '/vaults'
      fullPath: '/vaults/'
      preLoaderRoute: typeof AppVaultsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team/': {
      id: '/_app/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof AppTeamIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/invite/$token': {
      id: '/_auth/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AuthInviteTokenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/vaults/trash': {
      id: '/_app/vaults/trash'
      path: '/vaults/trash'
      fullPath: '/vaults/trash'
      preLoaderRoute: typeof AppVaultsTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vaults/$vaultId/': {
      id: '/_app/vaults/$vaultId/'
      path: '/vaults/$vaultId'
      fullPath: '/vaults/$vaultId/'
      preLoaderRoute: typeof AppVaultsVaultIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppHomeRoute: typeof AppHomeRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppVaultsTrashRoute: typeof AppVaultsTrashRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTeamIndexRoute: typeof AppTeamIndexRoute
  AppVaultsIndexRoute: typeof AppVaultsIndexRoute
  AppVaultsVaultIdIndexRoute: typeof AppVaultsVaultIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppHomeRoute: AppHomeRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppVaultsTrashRoute: AppVaultsTrashRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTeamIndexRoute: AppTeamIndexRoute,
  AppVaultsIndexRoute: AppVaultsIndexRoute,
  AppVaultsVaultIdIndexRoute: AppVaultsVaultIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoverRoute: typeof AuthRecoverRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthInviteTokenRoute: typeof AuthInviteTokenRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoverRoute: AuthRecoverRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthInviteTokenRoute: AuthInviteTokenRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
