/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Derive server session and verify client proof
 *
 * # Arguments
 * * `server_secret_ephemeral` - Server's secret ephemeral (from generate_server_ephemeral)
 * * `client_public_ephemeral` - Client's public ephemeral (received from client)
 * * `salt` - User's SRP salt (stored during registration)
 * * `verifier` - User's SRP verifier (stored during registration)
 * * `client_session_proof` - Client's proof (M1, received from client)
 *
 * # Returns
 * Session containing shared key and server proof (M2, sent to client for verification)
 *
 * # Errors
 * Returns error if client proof is invalid
 */
export declare function deriveServerSession(
	serverSecretEphemeral: string,
	clientPublicEphemeral: string,
	salt: string,
	verifier: string,
	clientSessionProof: string,
): Session;

export interface Ephemeral {
	public: string;
	secret: string;
}

/**
 * Generate server ephemeral key pair for SRP authentication
 *
 * # Arguments
 * * `verifier` - User's SRP verifier (stored during registration)
 *
 * # Returns
 * Server ephemeral containing public key (sent to client) and secret (kept server-side)
 */
export declare function generateServerEphemeral(verifier: string): Ephemeral;

export interface Session {
	key: string;
	proof: string;
}
