/* auto-generated by NAPI-RS */

export interface Ephemeral {
  public: string
  secret: string
}

export interface Session {
  key: string
  proof: string
}

/**
 * Generate server ephemeral key pair for SRP authentication
 * @param verifier - User's SRP verifier (stored during registration)
 * @returns Server ephemeral containing public key (sent to client) and secret (kept server-side)
 */
export function generateServerEphemeral(verifier: string): Ephemeral

/**
 * Derive server session and verify client proof
 * @param serverSecretEphemeral - Server's secret ephemeral (from generateServerEphemeral)
 * @param clientPublicEphemeral - Client's public ephemeral (received from client)
 * @param salt - User's SRP salt (stored during registration)
 * @param verifier - User's SRP verifier (stored during registration)
 * @param clientSessionProof - Client's proof (M1, received from client)
 * @returns Session containing shared key and server proof (M2, sent to client for verification)
 * @throws Error if client proof is invalid
 */
export function deriveServerSession(
  serverSecretEphemeral: string,
  clientPublicEphemeral: string,
  salt: string,
  verifier: string,
  clientSessionProof: string
): Session
