/// Command names are the ACL identity of the plugin: each one becomes an
/// `allow-…`/`deny-…` permission under `permissions/autogenerated/`, and
/// `permissions/default.toml` has to list them by hand.
const COMMANDS: &[&str] = &["share_text", "share_file"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
