#!/usr/bin/env bash
set -euo pipefail

# Bittery Self-Hosted Installer
# Usage:
#   Interactive:  curl -fsSL https://raw.githubusercontent.com/bittery-org/bittery/main/deploy/install.sh | bash
#   Non-interactive: bash install.sh --domain bittery.example.com --release 0.5.0 --install-dir /opt/bittery

REPO_BASE_URL="https://raw.githubusercontent.com/bittery-org/bittery"
DEFAULT_INSTALL_DIR="$HOME/bittery"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log()   { echo -e "${GREEN}[bittery]${NC} $1"; }
warn()  { echo -e "${YELLOW}[bittery]${NC} $1"; }
error() { echo -e "${RED}[bittery]${NC} $1" >&2; }

# Parse arguments
DOMAIN=""
DATABASE_URL=""
INSTALL_DIR=""
BITTERY_RELEASE=""
USE_BUILTIN_DB=true

while [[ $# -gt 0 ]]; do
  case $1 in
    --domain)       DOMAIN="$2"; shift 2 ;;
    --database-url) DATABASE_URL="$2"; USE_BUILTIN_DB=false; shift 2 ;;
    --install-dir)  INSTALL_DIR="$2"; shift 2 ;;
    --release)      BITTERY_RELEASE="${2#v}"; shift 2 ;;
    -h|--help)
      echo "Bittery Self-Hosted Installer"
      echo ""
      echo "Usage: install.sh [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --domain DOMAIN        Your domain name (e.g. bittery.example.com)"
      echo "  --database-url URL     External PostgreSQL connection string"
      echo "  --install-dir DIR      Installation directory (default: ~/bittery)"
      echo "  --release VERSION      Exact Bittery release shared by server and web"
      echo "  -h, --help             Show this help"
      exit 0
      ;;
    *) error "Unknown option: $1"; exit 1 ;;
  esac
done

# ── Prerequisites ──────────────────────────────────────────

check_prerequisites() {
  log "Checking prerequisites..."

  if ! command -v docker &>/dev/null; then
    error "Docker is not installed. Please install Docker first:"
    error "  https://docs.docker.com/engine/install/"
    exit 1
  fi

  if ! docker compose version &>/dev/null; then
    error "Docker Compose v2 is not installed."
    error "It should be included with Docker Desktop, or install the plugin:"
    error "  https://docs.docker.com/compose/install/"
    exit 1
  fi

  if ! command -v openssl &>/dev/null; then
    error "openssl is not installed. Please install it first."
    exit 1
  fi

  # Check if ports 80/443 are available
  for port in 80 443; do
    if ss -tlnp 2>/dev/null | grep -q ":${port} " || \
       lsof -i ":${port}" &>/dev/null 2>&1; then
      warn "Port ${port} appears to be in use. Caddy needs ports 80 and 443."
    fi
  done

  log "Prerequisites OK"
}

# ── Interactive prompts ────────────────────────────────────

prompt_config() {
  echo ""
  echo -e "${BLUE}╔══════════════════════════════════════╗${NC}"
  echo -e "${BLUE}║     Bittery Self-Hosted Installer    ║${NC}"
  echo -e "${BLUE}╚══════════════════════════════════════╝${NC}"
  echo ""

  # Domain
  if [[ -z "$DOMAIN" ]]; then
    read -rp "Enter your domain (e.g. bittery.example.com): " DOMAIN
    if [[ -z "$DOMAIN" ]]; then
      error "Domain is required"
      exit 1
    fi
  fi
  log "Domain: $DOMAIN"

  if [[ -z "$BITTERY_RELEASE" ]]; then
    read -rp "Enter the Bittery release to install (for example, 0.5.0): " BITTERY_RELEASE
    BITTERY_RELEASE="${BITTERY_RELEASE#v}"
  fi
  if [[ ! "$BITTERY_RELEASE" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    error "An exact stable release in X.Y.Z form is required"
    exit 1
  fi

  # Database
  if [[ -z "$DATABASE_URL" ]]; then
    echo ""
    echo "Database options:"
    echo "  1) Built-in PostgreSQL (recommended for most setups)"
    echo "  2) External PostgreSQL (bring your own)"
    read -rp "Choose [1]: " db_choice
    db_choice=${db_choice:-1}

    if [[ "$db_choice" == "2" ]]; then
      read -rp "Enter PostgreSQL connection string: " DATABASE_URL
      if [[ -z "$DATABASE_URL" ]]; then
        error "Database URL is required for external database"
        exit 1
      fi
      USE_BUILTIN_DB=false
    fi
  fi

  # Install directory
  if [[ -z "$INSTALL_DIR" ]]; then
    read -rp "Install directory [${DEFAULT_INSTALL_DIR}]: " INSTALL_DIR
    INSTALL_DIR=${INSTALL_DIR:-$DEFAULT_INSTALL_DIR}
  fi
}

# ── Generate secrets ───────────────────────────────────────

generate_secrets() {
  JWT_SECRET=$(openssl rand -hex 32)
  DB_PASSWORD=$(openssl rand -hex 16)
  log "Generated secrets"
}

# ── Download and configure ─────────────────────────────────

setup_files() {
  log "Setting up installation directory: $INSTALL_DIR"
  mkdir -p "$INSTALL_DIR"

  log "Downloading configuration files..."
  local release_source="${REPO_BASE_URL}/v${BITTERY_RELEASE}"
  curl -fsSL "${release_source}/deploy/docker/docker-compose.yml" -o "${INSTALL_DIR}/docker-compose.yml"
  curl -fsSL "${release_source}/deploy/docker/Caddyfile" -o "${INSTALL_DIR}/Caddyfile"

  # Write .env
  log "Writing configuration..."
  cat > "${INSTALL_DIR}/.env" <<EOF
# Bittery configuration — generated by installer
DOMAIN=${DOMAIN}
BITTERY_RELEASE=${BITTERY_RELEASE}
BITTERY_MODE=self-hosted
JWT_SECRET=${JWT_SECRET}
DB_PASSWORD=${DB_PASSWORD}
# Optional hardening
# CORS_ORIGIN must be a comma-separated list of bare origins.
# TRUST_PROXY_MODE can be none, cloudflare, or forwarded.
# BITTERY_ALLOW_INSECURE_HTTP defaults to false; enabling it still requires confirmation per client account.
# MINIO_ROOT_PASSWORD must be set before enabling the storage profile.
EOF

  if [[ -n "$DATABASE_URL" ]]; then
    echo "DATABASE_URL=${DATABASE_URL}" >> "${INSTALL_DIR}/.env"
  fi
}

# ── Start services ─────────────────────────────────────────

start_services() {
  cd "$INSTALL_DIR"

  COMPOSE_PROFILES=""
  if [[ "$USE_BUILTIN_DB" == true ]]; then
    COMPOSE_PROFILES="builtin-db"
  fi

  log "Pulling Docker images..."
  if [[ -n "$COMPOSE_PROFILES" ]]; then
    COMPOSE_PROFILES="$COMPOSE_PROFILES" docker compose pull
  else
    docker compose pull
  fi

  log "Starting Bittery..."
  if [[ -n "$COMPOSE_PROFILES" ]]; then
    COMPOSE_PROFILES="$COMPOSE_PROFILES" docker compose up -d
  else
    docker compose up -d
  fi

  # Wait for health
  log "Waiting for services to become healthy..."
  local retries=30
  while [[ $retries -gt 0 ]]; do
    if docker compose ps --format json 2>/dev/null | grep -q '"Health":"healthy"' || \
       docker compose ps 2>/dev/null | grep -q "(healthy)"; then
      break
    fi
    sleep 2
    retries=$((retries - 1))
  done

  if [[ $retries -eq 0 ]]; then
    warn "Services may still be starting. Check with: docker compose ps"
  fi
}

# ── Summary ────────────────────────────────────────────────

print_summary() {
  echo ""
  echo -e "${GREEN}╔══════════════════════════════════════╗${NC}"
  echo -e "${GREEN}║       Bittery is running! 🎉        ║${NC}"
  echo -e "${GREEN}╚══════════════════════════════════════╝${NC}"
  echo ""
  echo -e "  URL:         ${BLUE}https://${DOMAIN}${NC}"
  echo -e "  Install dir: ${INSTALL_DIR}"
  echo ""
  echo "  DNS: Make sure ${DOMAIN} points to this server's IP address."
  echo "  Caddy will automatically provision a TLS certificate."
  echo ""
  echo "  Useful commands:"
  echo "    cd ${INSTALL_DIR}"
  echo "    docker compose ps          # Check service status"
  echo "    docker compose logs -f     # View logs"
  echo "    docker compose down        # Stop services"
  echo "    Edit BITTERY_RELEASE in .env, then pull and restart server and web together to update."
  echo "    Set MINIO_ROOT_PASSWORD in .env before using: docker compose --profile storage up -d"
  echo ""
}

# ── Main ───────────────────────────────────────────────────

main() {
  check_prerequisites
  prompt_config
  generate_secrets
  setup_files
  start_services
  print_summary
}

main
