/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BackupRouteImport } from './routes/_backup'
import { Route as VaultRouteRouteImport } from './routes/vault/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultIndexRouteImport } from './routes/vault/index'
import { Route as VaultIdRouteRouteImport } from './routes/vault/$id/route'
import { Route as VaultIdIndexRouteImport } from './routes/vault/$id/index'
import { Route as VaultIdItemIdIndexRouteImport } from './routes/vault/$id/$itemId/index'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/_backup',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRouteRoute = VaultRouteRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultIdRouteRoute = VaultIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultIdIndexRoute = VaultIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultIdRouteRoute,
} as any)
const VaultIdItemIdIndexRoute = VaultIdItemIdIndexRouteImport.update({
  id: '/$itemId/',
  path: '/$itemId/',
  getParentRoute: () => VaultIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vault': typeof VaultRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/unlock': typeof UnlockRoute
  '/vault/$id': typeof VaultIdRouteRouteWithChildren
  '/vault/': typeof VaultIndexRoute
  '/vault/$id/': typeof VaultIdIndexRoute
  '/vault/$id/$itemId': typeof VaultIdItemIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unlock': typeof UnlockRoute
  '/vault': typeof VaultIndexRoute
  '/vault/$id': typeof VaultIdIndexRoute
  '/vault/$id/$itemId': typeof VaultIdItemIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vault': typeof VaultRouteRouteWithChildren
  '/_backup': typeof BackupRoute
  '/login': typeof LoginRoute
  '/unlock': typeof UnlockRoute
  '/vault/$id': typeof VaultIdRouteRouteWithChildren
  '/vault/': typeof VaultIndexRoute
  '/vault/$id/': typeof VaultIdIndexRoute
  '/vault/$id/$itemId/': typeof VaultIdItemIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vault'
    | '/login'
    | '/unlock'
    | '/vault/$id'
    | '/vault/'
    | '/vault/$id/'
    | '/vault/$id/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unlock'
    | '/vault'
    | '/vault/$id'
    | '/vault/$id/$itemId'
  id:
    | '__root__'
    | '/'
    | '/vault'
    | '/_backup'
    | '/login'
    | '/unlock'
    | '/vault/$id'
    | '/vault/'
    | '/vault/$id/'
    | '/vault/$id/$itemId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VaultRouteRoute: typeof VaultRouteRouteWithChildren
  BackupRoute: typeof BackupRoute
  LoginRoute: typeof LoginRoute
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_backup': {
      id: '/_backup'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/': {
      id: '/vault/'
      path: '/'
      fullPath: '/vault/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/$id': {
      id: '/vault/$id'
      path: '/$id'
      fullPath: '/vault/$id'
      preLoaderRoute: typeof VaultIdRouteRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/vault/$id/': {
      id: '/vault/$id/'
      path: '/'
      fullPath: '/vault/$id/'
      preLoaderRoute: typeof VaultIdIndexRouteImport
      parentRoute: typeof VaultIdRouteRoute
    }
    '/vault/$id/$itemId/': {
      id: '/vault/$id/$itemId/'
      path: '/$itemId'
      fullPath: '/vault/$id/$itemId'
      preLoaderRoute: typeof VaultIdItemIdIndexRouteImport
      parentRoute: typeof VaultIdRouteRoute
    }
  }
}

interface VaultIdRouteRouteChildren {
  VaultIdIndexRoute: typeof VaultIdIndexRoute
  VaultIdItemIdIndexRoute: typeof VaultIdItemIdIndexRoute
}

const VaultIdRouteRouteChildren: VaultIdRouteRouteChildren = {
  VaultIdIndexRoute: VaultIdIndexRoute,
  VaultIdItemIdIndexRoute: VaultIdItemIdIndexRoute,
}

const VaultIdRouteRouteWithChildren = VaultIdRouteRoute._addFileChildren(
  VaultIdRouteRouteChildren,
)

interface VaultRouteRouteChildren {
  VaultIdRouteRoute: typeof VaultIdRouteRouteWithChildren
  VaultIndexRoute: typeof VaultIndexRoute
}

const VaultRouteRouteChildren: VaultRouteRouteChildren = {
  VaultIdRouteRoute: VaultIdRouteRouteWithChildren,
  VaultIndexRoute: VaultIndexRoute,
}

const VaultRouteRouteWithChildren = VaultRouteRoute._addFileChildren(
  VaultRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VaultRouteRoute: VaultRouteRouteWithChildren,
  BackupRoute: BackupRoute,
  LoginRoute: LoginRoute,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
