// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "bittery-crypto-react-native.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNNativeModuleSpec.h"

@interface CryptoReactNative : NSObject <NativeCryptoReactNativeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface CryptoReactNative : NSObject <RCTBridgeModule>
#endif

@end