// Generated by uniffi-bindgen-react-native
// Export the generated bindings to the app.
export * from './generated/bittery_crypto_api';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as bittery_crypto_api from './generated/bittery_crypto_api';

import initAsync from './generated/wasm-bindgen/index.js';
const wasmPath = new URL('./generated/wasm-bindgen/index_bg.wasm', import.meta.url);

export async function uniffiInitAsync() {
  await initAsync({ module_or_path: wasmPath })

  // Initialize the generated bindings: mostly checksums, but also callbacks.
  // - the boolean flag ensures this loads exactly once, even if the JS code
  //   is reloaded (e.g. during development with metro).
  bittery_crypto_api.default.initialize();
}

// Export the crates as individually namespaced objects.
export default {
  bittery_crypto_api,
};

