// Field type patterns with weights for scoring
export const FIELD_PATTERNS = {
	username: {
		namePatterns: [
			/user/i,
			/login/i,
			/account/i,
			/identifier/i,
			/uid/i,
			/handle/i,
		],
		idPatterns: [
			/user/i,
			/login/i,
			/account/i,
			/identifier/i,
			/uid/i,
			/handle/i,
		],
		placeholderPatterns: [
			/user/i,
			/login/i,
			/account/i,
			/enter.*name/i,
			/your.*name/i,
		],
		autocompleteValues: ["username", "user", "nickname"],
		labelPatterns: [/user/i, /login/i, /account/i, /sign.*in/i, /identifier/i],
		ariaLabelPatterns: [/user/i, /login/i, /account/i, /sign.*in/i],
	},
	email: {
		typeValues: ["email"],
		namePatterns: [/email/i, /e-mail/i, /mail/i],
		idPatterns: [/email/i, /e-mail/i, /mail/i],
		placeholderPatterns: [/email/i, /e-mail/i, /@/],
		autocompleteValues: ["email", "username email"],
		labelPatterns: [/email/i, /e-mail/i],
		ariaLabelPatterns: [/email/i, /e-mail/i],
	},
	password: {
		typeValues: ["password"],
		namePatterns: [/pass/i, /pwd/i, /secret/i, /credential/i],
		idPatterns: [/pass/i, /pwd/i, /secret/i, /credential/i],
		placeholderPatterns: [/pass/i, /pwd/i, /secret/i],
		autocompleteValues: ["current-password", "new-password", "password", "off"],
		labelPatterns: [/password/i, /passwort/i, /contraseña/i, /mot.*passe/i],
		ariaLabelPatterns: [/password/i, /passwort/i, /contraseña/i, /mot.*passe/i],
	},
	otp: {
		namePatterns: [
			/otp/i,
			/code/i,
			/verify/i,
			/token/i,
			/pin/i,
			/2fa/i,
			/mfa/i,
		],
		idPatterns: [/otp/i, /code/i, /verify/i, /token/i, /pin/i, /2fa/i, /mfa/i],
		placeholderPatterns: [/code/i, /otp/i, /verify/i, /digit/i, /pin/i, /2fa/i],
		autocompleteValues: ["one-time-code"],
		labelPatterns: [
			/verification/i,
			/code/i,
			/otp/i,
			/2fa/i,
			/two.*factor/i,
			/mfa/i,
		],
		ariaLabelPatterns: [/verification/i, /code/i, /otp/i, /2fa/i],
		// OTP fields often have specific attributes
		maxLengthValues: [1, 4, 5, 6, 7, 8],
		inputModeValues: ["numeric", "tel"],
	},
	phone: {
		typeValues: ["tel"],
		namePatterns: [/phone/i, /mobile/i, /cell/i, /tel/i, /contact/i],
		idPatterns: [/phone/i, /mobile/i, /cell/i, /tel/i],
		placeholderPatterns: [/phone/i, /mobile/i, /\+?[0-9]/],
		autocompleteValues: ["tel", "tel-national", "tel-local", "mobile"],
		labelPatterns: [/phone/i, /mobile/i, /cell/i, /telephone/i],
		ariaLabelPatterns: [/phone/i, /mobile/i, /telephone/i],
	},
	name: {
		namePatterns: [
			/^name$/i,
			/fullname/i,
			/full.*name/i,
			/firstname/i,
			/first.*name/i,
			/lastname/i,
			/last.*name/i,
		],
		idPatterns: [
			/^name$/i,
			/fullname/i,
			/firstname/i,
			/lastname/i,
			/displayname/i,
		],
		placeholderPatterns: [/your.*name/i, /full.*name/i, /first.*name/i],
		autocompleteValues: ["name", "given-name", "family-name"],
		labelPatterns: [/^name$/i, /full.*name/i, /first.*name/i, /last.*name/i],
		ariaLabelPatterns: [/^name$/i, /full.*name/i],
	},
	// Credit card field patterns
	cardNumber: {
		namePatterns: [
			/card.*num/i,
			/cardnum/i,
			/cc.*num/i,
			/ccnum/i,
			/credit.*card/i,
			/card.*no/i,
			/pan/i,
		],
		idPatterns: [
			/card.*num/i,
			/cardnum/i,
			/cc.*num/i,
			/ccnum/i,
			/credit.*card/i,
			/card.*no/i,
			/pan/i,
		],
		placeholderPatterns: [
			/card.*number/i,
			/credit.*card/i,
			/4242/i,
			/1234.*5678/i,
			/xxxx.*xxxx/i,
			/•••• ••••/i,
		],
		autocompleteValues: ["cc-number"],
		labelPatterns: [
			/card.*number/i,
			/credit.*card/i,
			/debit.*card/i,
			/numéro.*carte/i,
			/kartennummer/i,
			/número.*tarjeta/i,
		],
		ariaLabelPatterns: [/card.*number/i, /credit.*card/i],
		// Card number fields typically have specific attributes
		maxLengthValues: [16, 19, 23],
		inputModeValues: ["numeric"],
	},
	cardExpiry: {
		namePatterns: [
			/exp/i,
			/expir/i,
			/valid/i,
			/cc.*exp/i,
			/card.*exp/i,
			/mm.*yy/i,
		],
		idPatterns: [/exp/i, /expir/i, /valid/i, /cc.*exp/i, /card.*exp/i],
		placeholderPatterns: [
			/mm\s*\/\s*yy/i,
			/mm\/yy/i,
			/expir/i,
			/valid.*thru/i,
			/valid.*until/i,
		],
		autocompleteValues: ["cc-exp", "cc-exp-month", "cc-exp-year"],
		labelPatterns: [
			/expir/i,
			/exp.*date/i,
			/valid.*thru/i,
			/valid.*until/i,
			/gültig.*bis/i,
			/fecha.*vencimiento/i,
		],
		ariaLabelPatterns: [/expir/i, /valid/i],
		maxLengthValues: [5, 7],
	},
	cardCvv: {
		namePatterns: [
			/cvv/i,
			/cvc/i,
			/cid/i,
			/cvn/i,
			/security.*code/i,
			/sec.*code/i,
			/card.*code/i,
		],
		idPatterns: [
			/cvv/i,
			/cvc/i,
			/cid/i,
			/cvn/i,
			/security.*code/i,
			/sec.*code/i,
		],
		placeholderPatterns: [
			/cvv/i,
			/cvc/i,
			/cid/i,
			/security.*code/i,
			/\d{3,4}/,
			/•••/i,
		],
		autocompleteValues: ["cc-csc"],
		labelPatterns: [
			/cvv/i,
			/cvc/i,
			/cid/i,
			/security.*code/i,
			/card.*verification/i,
			/sicherheitscode/i,
			/código.*seguridad/i,
		],
		ariaLabelPatterns: [/cvv/i, /cvc/i, /security.*code/i],
		maxLengthValues: [3, 4],
		inputModeValues: ["numeric"],
	},
	cardName: {
		namePatterns: [
			/card.*holder/i,
			/cardholder/i,
			/cc.*name/i,
			/ccname/i,
			/name.*on.*card/i,
			/card.*name/i,
		],
		idPatterns: [
			/card.*holder/i,
			/cardholder/i,
			/cc.*name/i,
			/ccname/i,
			/name.*on.*card/i,
		],
		placeholderPatterns: [
			/name.*on.*card/i,
			/cardholder/i,
			/full.*name/i,
			/as.*on.*card/i,
		],
		autocompleteValues: ["cc-name"],
		labelPatterns: [
			/name.*on.*card/i,
			/cardholder.*name/i,
			/card.*holder/i,
			/nom.*sur.*carte/i,
			/karteninhaber/i,
			/titular.*tarjeta/i,
		],
		ariaLabelPatterns: [/name.*on.*card/i, /cardholder/i],
	},
	// Identity field patterns
	firstName: {
		namePatterns: [
			/^first/i,
			/firstname/i,
			/first.*name/i,
			/fname/i,
			/given.*name/i,
			/forename/i,
		],
		idPatterns: [
			/^first/i,
			/firstname/i,
			/first.*name/i,
			/fname/i,
			/given.*name/i,
		],
		placeholderPatterns: [/first.*name/i, /given.*name/i, /forename/i],
		autocompleteValues: ["given-name"],
		labelPatterns: [
			/first.*name/i,
			/given.*name/i,
			/forename/i,
			/prénom/i,
			/vorname/i,
			/nombre/i,
		],
		ariaLabelPatterns: [/first.*name/i, /given.*name/i],
	},
	lastName: {
		namePatterns: [
			/^last/i,
			/lastname/i,
			/last.*name/i,
			/lname/i,
			/surname/i,
			/family.*name/i,
		],
		idPatterns: [
			/^last/i,
			/lastname/i,
			/last.*name/i,
			/lname/i,
			/surname/i,
			/family.*name/i,
		],
		placeholderPatterns: [/last.*name/i, /surname/i, /family.*name/i],
		autocompleteValues: ["family-name"],
		labelPatterns: [
			/last.*name/i,
			/surname/i,
			/family.*name/i,
			/nom.*famille/i,
			/nachname/i,
			/apellido/i,
		],
		ariaLabelPatterns: [/last.*name/i, /surname/i, /family.*name/i],
	},
	street: {
		namePatterns: [
			/street/i,
			/address/i,
			/addr/i,
			/address.*1/i,
			/address.*line/i,
			/street.*addr/i,
			/shipping.*address/i,
			/billing.*address/i,
		],
		idPatterns: [
			/street/i,
			/address/i,
			/addr/i,
			/address.*1/i,
			/address.*line/i,
		],
		placeholderPatterns: [
			/street/i,
			/address/i,
			/123.*main/i,
			/enter.*address/i,
		],
		autocompleteValues: [
			"street-address",
			"address-line1",
			"address-line2",
			"shipping street-address",
			"billing street-address",
		],
		labelPatterns: [
			/street/i,
			/address/i,
			/addr/i,
			/adresse/i,
			/dirección/i,
			/住所/i,
		],
		ariaLabelPatterns: [/street/i, /address/i],
	},
	city: {
		namePatterns: [/city/i, /town/i, /locality/i, /suburb/i, /municipality/i],
		idPatterns: [/city/i, /town/i, /locality/i, /suburb/i],
		placeholderPatterns: [/city/i, /town/i, /enter.*city/i],
		autocompleteValues: ["address-level2", "locality"],
		labelPatterns: [
			/city/i,
			/town/i,
			/locality/i,
			/ville/i,
			/stadt/i,
			/ciudad/i,
			/市/i,
		],
		ariaLabelPatterns: [/city/i, /town/i, /locality/i],
	},
	state: {
		namePatterns: [
			/state/i,
			/province/i,
			/region/i,
			/prefecture/i,
			/county/i,
			/territory/i,
		],
		idPatterns: [/state/i, /province/i, /region/i, /prefecture/i],
		placeholderPatterns: [/state/i, /province/i, /region/i, /select.*state/i],
		autocompleteValues: ["address-level1", "region"],
		labelPatterns: [
			/state/i,
			/province/i,
			/region/i,
			/prefecture/i,
			/county/i,
			/état/i,
			/bundesland/i,
			/provincia/i,
			/県/i,
		],
		ariaLabelPatterns: [/state/i, /province/i, /region/i],
	},
	postalCode: {
		namePatterns: [/zip/i, /postal/i, /postcode/i, /post.*code/i, /zip.*code/i],
		idPatterns: [/zip/i, /postal/i, /postcode/i, /post.*code/i],
		placeholderPatterns: [/zip/i, /postal/i, /postcode/i, /\d{5}/],
		autocompleteValues: ["postal-code"],
		labelPatterns: [
			/zip/i,
			/postal.*code/i,
			/postcode/i,
			/post.*code/i,
			/code.*postal/i,
			/plz/i,
			/código.*postal/i,
			/郵便番号/i,
		],
		ariaLabelPatterns: [/zip/i, /postal/i, /postcode/i],
		maxLengthValues: [5, 6, 7, 9, 10],
	},
	country: {
		namePatterns: [/country/i, /nation/i, /country.*code/i],
		idPatterns: [/country/i, /nation/i],
		placeholderPatterns: [/country/i, /select.*country/i],
		autocompleteValues: ["country", "country-name"],
		labelPatterns: [/country/i, /nation/i, /pays/i, /land/i, /país/i, /国/i],
		ariaLabelPatterns: [/country/i, /nation/i],
	},
	dateOfBirth: {
		typeValues: ["date"],
		namePatterns: [
			/dob/i,
			/birth/i,
			/birthday/i,
			/date.*birth/i,
			/bday/i,
			/born/i,
		],
		idPatterns: [/dob/i, /birth/i, /birthday/i, /date.*birth/i, /bday/i],
		placeholderPatterns: [
			/birth/i,
			/birthday/i,
			/mm\/dd\/yyyy/i,
			/dd\/mm\/yyyy/i,
		],
		autocompleteValues: ["bday", "birthday"],
		labelPatterns: [
			/date.*birth/i,
			/birth.*date/i,
			/birthday/i,
			/dob/i,
			/date.*naissance/i,
			/geburtsdatum/i,
			/fecha.*nacimiento/i,
			/生年月日/i,
		],
		ariaLabelPatterns: [/birth/i, /birthday/i, /dob/i],
	},
};

// Multi-step form indicators
export const MULTI_STEP_INDICATORS = {
	// Classes that suggest multi-step forms
	stepClasses: [
		/step/i,
		/wizard/i,
		/stage/i,
		/phase/i,
		/page/i,
		/slide/i,
		/tab.*panel/i,
		/carousel/i,
	],
	// Navigation elements
	navSelectors: [
		".steps",
		".wizard-steps",
		".step-indicator",
		".progress-steps",
		'[role="progressbar"]',
		".form-steps",
		".multi-step",
	],
	// Next/Previous button patterns
	buttonPatterns: [
		/next/i,
		/continue/i,
		/proceed/i,
		/forward/i,
		/weiter/i,
		/suivant/i,
		/previous/i,
		/back/i,
		/zurück/i,
	],
	// Hidden step containers
	hiddenStepSelectors: [
		'.step[style*="display: none"]',
		'.step[style*="visibility: hidden"]',
		".step.hidden",
		".step.inactive",
		'[data-step]:not([data-step="current"])',
		".form-step:not(.active)",
	],
};
