/// Command names are the ACL identity of the plugin: each one becomes an
/// `allow-…`/`deny-…` permission under `permissions/autogenerated/`, and
/// `permissions/default.toml` has to list them by hand.
///
/// One entry for now. The commands that replace the Expo module bridge — vault
/// sync, MUK escrow, passkey mutations — arrive in the next chunk.
const COMMANDS: &[&str] = &["is_supported"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
