/// Command names are the ACL identity of the plugin: each one becomes an
/// `allow-…`/`deny-…` permission under `permissions/autogenerated/`, and
/// `permissions/default.toml` has to list them by hand.
///
/// This list, `invoke_handler!` in `src/lib.rs` and `permissions/default.toml` must
/// agree exactly. A command missing from here has no permission to grant and is
/// unreachable; one missing from `lib.rs` mints a permission for nothing.
const COMMANDS: &[&str] = &[
    // Vault state
    "set_master_unlock_key",
    "set_muk_auto_lock_timeout",
    "clear_master_unlock_key",
    "clear_all_master_unlock_keys",
    "is_vault_unlocked",
    "get_master_unlock_key_base64",
    // MUK escrow
    "escrow_muk_with_biometric",
    "retrieve_escrowed_muk",
    "has_valid_escrow",
    "has_valid_escrow_for_email",
    "get_escrow_remaining_time",
    "clear_escrow",
    // Sync
    "sync_vault_data",
    "get_pending_passkey_mutations",
    "mark_pending_passkey_mutations_applied",
    "mark_pending_passkey_mutations_failed",
    // 30-day master password re-entry
    "is_master_password_reentry_required",
    "can_use_biometric_unlock",
    "update_last_master_password_entry",
    "get_last_master_password_entry",
    // Capability
    "is_available",
    "is_biometric_available",
    "open_credential_provider_settings",
    "is_supported",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
